name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ deco }}
          GIST_ID: ${{https://gist.github.com/Youngseo-Jeon0313/279e6bf8c2617d49bd350cea34e0b75a}}
          TIMEZONE: Asia/Seoul
